spring:
  application:
    name: service-a
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: "*"