server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Facultate/JavaTechnologies/Homework2/labtwo-advanced/config-repo
          default-label: master